---

plugins: [flowtype]

env:
  node: true

extends:
  - 'airbnb/base'
  - plugin:import/errors
  - plugin:import/warnings

rules:
  no-underscore-dangle: 0
  no-plusplus: 0
  no-unused-expressions:
    - error
    - allowTernary: true

  no-use-before-define:
    - error
    - functions: false
